version: "3.3"

services:
  reverse_proxy:
    image: nginx:1.23.2-alpine
    ports:
      - 80:80
    volumes:
      - ./reverse_proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - riesgos-wps

  riesgos-wps:
    image: gfzriesgos/riesgos-wps:latest
    restart: always
    env_file:
      - .env
    environment:
      - CATALINA_OPTS=${riesgosWpsCatalinaOpts}
      - RIESGOS_MAX_CACHE_SIZE_MB=${riesgosWpsMaxCacheSizeMb}
      - RIESGOS_GEOSERVER_ACCESS_BASE_URL=${riesgosWpsGeoserverAccessBaseUrl}
      - RIESGOS_GEOSERVER_SEND_BASE_URL=${riesgosWpsGeoserverSendBaseUrl}
      - RIESGOS_GEOSERVER_USERNAME=${riesgosWpsGeoserverUsername}
      - RIESGOS_GEOSERVER_PASSWORD=${riesgosWpsGeoserverPassword}
    volumes:
      # We need to pass the docker.sock as the WPS itself needs to run
      # docker commands
      - "/var/run/docker.sock:/var/run/docker.sock"
      # We also want a volume for the riesgos-json-config files.
      # As it is where the processes are defined.
      - "./configs:/usr/share/riesgos/json-configurations"
      - "tomcat-folder:/usr/local/tomcat"

  wps-init:
    image: python:3.10.5-alpine3.15
    entrypoint: "/entrypoint.sh"
    depends_on:
      - riesgos-wps
    environment:
      RIESGOS_GEOSERVER_SEND_BASE_URL: ${riesgosWpsGeoserverSendBaseUrl}
      RIESGOS_GEOSERVER_PASSWORD: ${riesgosWpsGeoserverPassword}
      RIESGOS_GEOSERVER_USERNAME: ${riesgosWpsGeoserverUsername}
      RIESGOS_WPS_ACCESS_SERVER_HOST: ${riesgosWpsAccessServerHost}
      RIESGOS_WPS_ACCESS_SERVER_PORT: ${riesgosWpsAccessServerPort}
      RIESGOS_WPS_ACCESS_SERVER_PROTOCOL: ${riesgosWpsAccessServerProtocol}
      RIESGOS_WPS_PASSWORD: ${riesgosWpsPassword}
      RIESGOS_WPS_SEND_BASE_URL: ${riesgosWpsSendBaseUrl}
      RIESGOS_WPS_TOMCAT_USERNAME: ${riesgosWpsTomcatUsername}
      RIESGOS_WPS_TOMCAT_PASSWORD: ${riesgosWpsTomcatPassword}
    volumes:
      - "./wps/init/entrypoint.sh:/entrypoint.sh"
      - "./wps/init/init_wps.py:/init_wps.py"
      - "tomcat-folder:/tomcat"
      - "./styles:/styles"
    env_file:
      - .env

volumes:
  tomcat-folder:
